{{- if .Values.prometheusRule.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "robyn-runtime.fullname" . }}
  labels:
    {{- include "robyn-runtime.labels" . | nindent 4 }}
    {{- with .Values.prometheusRule.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- with .Values.prometheusRule.groups }}
  groups:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
