{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "robyn-runtime.fullname" . }}
  labels:
    {{- include "robyn-runtime.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- with .Values.secrets.data }}
  {{- range $key, $value := . }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
{{- end }}
